export const INITIALIZE_PROJECT_DATA = "INITIALIZE_PROJECT_DATA";
export const INITIALIZE_PROJECT_DATA_SUCCESS =
  "INITIALIZE_PROJECT_DATA_SUCCESS";

export const INITIALIZE_PROJECT_DATA_ERROR = "INITIALIZE_PROJECT_DATA_ERROR";
