export const INITIALIZE_PROJECT_DATA = "INITIALIZE_PROJECT_DATA";
export const INITIALIZE_PROJECT_DATA_SUCCESS =
  "INITIALIZE_PROJECT_DATA_SUCCESS";

export const INITIALIZE_PROJECT_DATA_ERROR = "INITIALIZE_PROJECT_DATA_ERROR";

export const SET_PROJECT_ACTIVE_TAB = "SET_PROJECT_TAB";
export const SET_PROJECT_SEARCH_QUERY = "SET_PROJECT_SEARCH_QUERY";
