export const INITIALIZE_EXPERIENCE_DATA = "INITIALIZE_EXPERIENCE_DATA";
export const INITIALIZE_EXPERIENCE_DATA_SUCCESS =
  "INITIALIZE_EXPERIENCE_SUCCESS";

export const INITIALIZE_EXPERIENCE_DATA_ERROR =
  "INITIALIZE_EXPERIENCE_DATA_ERROR";
export const CLEAR_EXPERIENCE_ERRORS = "CLEAR_EXPERIENCE_ERRORS";
