export const INITIALIZE_PORTFOLIO = "INITIALIZE_PORTFOLIO";
export const SET_DEVICE_STATUS = "SET_DEVICE_STATUS";

export const SET_DATA_PENDING = "SET_DATA_PENDING";
export const SET_DATA_RECEIVED = "SET_DATA_RECEIVED";
