export const REQUEST_SEND_MESSAGE = "REQUEST_SEND_MESSAGE";

export const SET_MESSAGE_SENT = "SET_MESSAGE_SENT";

export const SET_MESSAGE_ERROR = "SET_MESSAGE_ERROR";
export const CLEAR_MESSAGE_ERRORS = "CLEAR_MESSAGE_ERRORS";
