export const SET_ADMIN_VISIBLE = "SET_ADMIN_VISIBLE";
export const SET_ADMIN_HIDDEN = "SET_ADMIN_HIDDEN";

export const REQUEST_ADMIN_AUTHENTICATION = "REQUEST_ADMIN_AUTHENTICATION";
export const SET_ADMIN_AUTHENTICATED = "SET_ADMIN_AUTHENTICATED";

export const SET_ACTIVE_ADMIN_TAB = "SET_ACTIVE_ADMIN_TAB";
export const SET_ADMIN_SEARCH_QUERY = "SET_ADMIN_SEARCH_QUERY";

export const REQUEST_ITEM_UPDATE = "REQUEST_ITEM_UPDATE";
export const REQUST_ITEM_DELETION = "REQUEST_ITEM_DELETION";
export const REQUEST_ITEM_CREATION = "REQUEST_ITEM_CREATION";
