export const SET_ADMIN_VISIBLE = "SET_ADMIN_VISIBLE";
export const SET_ADMIN_HIDDEN = "SET_ADMIN_HIDDEN";

export const REQUEST_ADMIN_AUTHENTICATION = "REQUEST_ADMIN_AUTHENTICATION";
export const SET_ADMIN_AUTHENTICATED = "SET_ADMIN_AUTHENTICATED";
