export const INITIALIZE_BLOG_DATA = "INITIALIZE_BLOG_DATA";
export const INITIALIZE_BLOG_DATA_SUCCESS = "INITIALIZE_BLOG_DATA_SUCCESS";

export const INITIALIZE_BLOG_DATA_ERROR = "INITIALIZE_BLOG_DATA_ERROR";
export const CLEAR_BLOG_ERRORS = "CLEAR_BLOG_ERRORS";
